---
# Add user to the correct group
# usermod -aG dialout public
- group: name=[[items]] state=present
  with_items:
  - dialout
  - btsync
  - tty

# Add the user to the groups listed above
- user: name=[[items]] shell=/bin/bash groups=dialout,btsync,tty append=yes createhome=yes
  with_items:
  - public
  - it
  - remote

